name: cypress-ppc64le
on:
  # See the documentation for more intricate event dispatch here:
  # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  workflow_dispatch:
jobs:
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Use ppc64le environment
      run: >-
        docker run -it w --platform ppc64le ubuntu:22:04

    - name: Docker Build ppc64le
      env:
       DOCKER_BUILDKIT: 1
      run: docker build -t localhost/quay-local:latest .

    - name: Start Quay
      run: |
        docker-compose up -d redis quay-db
        docker exec -t quay-db bash -c 'while ! pg_isready; do echo "waiting for postgres"; sleep 2; done'
        DOCKER_USER="1001:0" docker-compose up -d --no-build quay

    - name: Checkout
      uses: actions/checkout@v3

    - name: Seed Database
      run: cd web && npm run quay:seed

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Integration Test
      run:  |
        docker restart quay-quay
        sleep 30
        make integration-test

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        build: npm run build
        start: npm run start:integration
        wait-on: 'http://localhost:9000'
        wait-on-timeout: 120
        working-directory: web
      env:
        REACT_QUAY_APP_API_URL: http://localhost:8080

    - name: Docker exit
      run: exit

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: web/cypress/screenshots

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: web/cypress/videos

